create table actors
(
    id        integer generated by default as identity
        primary key,
    full_name varchar(255)
);

alter table actors
    owner to postgres;

create table countries
(
    id   integer generated by default as identity
        primary key,
    name varchar(255)
);

alter table countries
    owner to postgres;

create table genres
(
    id   integer generated by default as identity
        primary key,
    name varchar(255)
);

alter table genres
    owner to postgres;

create table media
(
    id      varchar(255) not null
        primary key,
    poster  varchar(255),
    trailer varchar(255)
);

alter table media
    owner to postgres;

create table movie_details
(
    id              varchar(255) not null
        primary key,
    description     varchar(255),
    director        varchar(255),
    duration        integer,
    production_year integer,
    country_id      integer
        constraint fkqq43k1gd79fml19b3ss7fqunv
            references countries,
    media_id        varchar(255)
        constraint fkcpny4tmi2ufvcnggwd0jgqdlt
            references media
);

alter table movie_details
    owner to postgres;

create table movie_details_actors
(
    movie_details_id varchar(255) not null
        constraint fk3edtpdtubjhbag5ess3hjdw0o
            references movie_details,
    actor_id         integer      not null
        constraint fkcxnm90yk3pc5qmndc8sj6mc8d
            references actors,
    primary key (movie_details_id, actor_id)
);

alter table movie_details_actors
    owner to postgres;

create table movie_details_genres
(
    movie_details_id varchar(255) not null
        constraint fkfxt4hlsrjve8bmwcki0p2dokc
            references movie_details,
    genres_id        integer      not null
        constraint fk5ayw8r0ji0uhu9oxouokr1vxn
            references genres,
    primary key (movie_details_id, genres_id)
);

alter table movie_details_genres
    owner to postgres;

create table roles
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
        constraint uk_ofx66keruapi6vyqpv6f2or37
            unique
);

alter table roles
    owner to postgres;

create table sessions
(
    id               varchar(255) not null
        primary key,
    name             varchar(255),
    start_time       timestamp,
    movie_details_id varchar(255)
        constraint fkm9nl4yfdexdjq1fy6jmmpvi8k
            references movie_details
);

alter table sessions
    owner to postgres;

create table ticket_types
(
    id   varchar(255) not null
        primary key,
    name varchar(255)
);

alter table ticket_types
    owner to postgres;

create table users
(
    id       varchar(255) not null
        primary key,
    email    varchar(255)
        constraint uk_6dotkott2kjsp8vw4d0m25fb7
            unique,
    login    varchar(255) not null
        constraint uk_ow0gan20590jrb00upg3va2fn
            unique,
    password varchar(255) not null
);

alter table users
    owner to postgres;

create table tickets
(
    id             varchar(255) not null
        primary key,
    price          integer,
    row            integer,
    seat           integer,
    session_id     varchar(255)
        constraint fk6yhwfajgdoqa8kq4gnuimtkpp
            references sessions,
    ticket_type_id varchar(255)
        constraint fkotik7mbbb14hu8n9og7o92k5h
            references ticket_types,
    user_id        varchar(255)
        constraint fk4eqsebpimnjen0q46ja6fl2hl
            references users
);

alter table tickets
    owner to postgres;

create table users_roles
(
    user_id varchar(255) not null
        constraint fk2o0jvgh89lemvvo17cbqvdxaa
            references users,
    role_id bigint       not null
        constraint fkj6m8fwv7oqv74fcehir1a9ffy
            references roles,
    primary key (user_id, role_id)
);

alter table users_roles
    owner to postgres;

